name: Android Build

on:
  push:
    branches: [ main ]
    paths:
      - 'nutrition_ai_mobile/**'
      - '.github/workflows/android-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'nutrition_ai_mobile/**'

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      - name: Flutter pub get
        working-directory: nutrition_ai_mobile
        run: flutter pub get

      - name: Build APK (release)
        working-directory: nutrition_ai_mobile
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: nutrition-ai-android-apk
          path: nutrition_ai_mobile/build/app/outputs/flutter-apk/app-release.apk

