name: Flutter Build APK

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'nutrition_ai_mobile/**'
      - '.github/workflows/flutter-build.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'nutrition_ai_mobile/**'
      - '.github/workflows/flutter-build.yml'
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'release'
        type: choice
        options:
        - release
        - debug

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: nutrition_ai_mobile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Verify Flutter installation
        run: flutter doctor -v

      - name: Run Flutter tests
        run: flutter test --coverage
        continue-on-error: true

      - name: Build APK (Release)
        if: github.event.inputs.build_type != 'debug' && github.event_name != 'pull_request'
        run: flutter build apk --release --split-per-abi

      - name: Build APK (Debug)
        if: github.event.inputs.build_type == 'debug' || github.event_name == 'pull_request'
        run: flutter build apk --debug

      - name: Get build info
        id: build_info
        run: |
          if [ "${{ github.event.inputs.build_type }}" = "debug" ] || [ "${{ github.event_name }}" = "pull_request" ]; then
            APK_PATH="build/app/outputs/flutter-apk/app-debug.apk"
            BUILD_TYPE="debug"
          else
            APK_PATH="build/app/outputs/flutter-apk/app-arm64-v8a-release.apk"
            BUILD_TYPE="release"
          fi
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
          echo "build_type=$BUILD_TYPE" >> $GITHUB_OUTPUT
          
          # Get APK size
          if [ -f "$APK_PATH" ]; then
            APK_SIZE=$(du -h "$APK_PATH" | cut -f1)
            echo "apk_size=$APK_SIZE" >> $GITHUB_OUTPUT
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: nutricoach-mobile-${{ steps.build_info.outputs.build_type }}-${{ github.run_number }}
          path: |
            nutrition_ai_mobile/build/app/outputs/flutter-apk/*.apk
            nutrition_ai_mobile/build/app/outputs/flutter-apk/*.apk.sha1
          retention-days: 30

      - name: Upload release APKs to release
        if: startsWith(github.ref, 'refs/tags/v') && github.event.inputs.build_type != 'debug'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            nutrition_ai_mobile/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            nutrition_ai_mobile/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            nutrition_ai_mobile/build/app/outputs/flutter-apk/app-x86_64-release.apk
          name: NutriCoach Mobile v${{ github.ref_name }}
          body: |
            ## NutriCoach Mobile App - ${{ github.ref_name }}
            
            ### 📱 Download Options
            - **ARM64** (Recommended for most modern devices): `app-arm64-v8a-release.apk`
            - **ARM32** (Older 32-bit ARM devices): `app-armeabi-v7a-release.apk`
            - **x86_64** (Emulators and x86 devices): `app-x86_64-release.apk`
            
            ### 🔧 Installation
            1. Enable "Install from unknown sources" in Android settings
            2. Download the appropriate APK for your device
            3. Open the APK file to install
            4. Configure server URL in app settings
            
            ### 📋 Requirements
            - Android 5.0 (API level 21) or higher
            - NutriCoach backend server running
            
            ### 🆕 What's New
            See [Changelog](https://github.com/chartmann1590/NutriCoach-AI/wiki/Changelog) for full details.
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR with APK info
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = 'nutrition_ai_mobile/${{ steps.build_info.outputs.apk_path }}';
            const stats = fs.statSync(path);
            const fileSizeInBytes = stats.size;
            const fileSizeInMB = (fileSizeInBytes / (1024*1024)).toFixed(2);
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 📱 Flutter APK Built Successfully!
              
              **APK Details:**
              - **Build Type:** ${{ steps.build_info.outputs.build_type }}
              - **Size:** ${fileSizeInMB} MB
              - **Artifact:** \`nutricoach-mobile-${{ steps.build_info.outputs.build_type }}-${{ github.run_number }}\`
              
              **Download:** Check the "Artifacts" section in this workflow run to download the APK.
              
              **Test Installation:**
              1. Download the APK from artifacts
              2. Enable "Install from unknown sources" on your Android device
              3. Install the APK
              4. Configure server URL in app settings`
            });

  build-web:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    
    defaults:
      run:
        working-directory: nutrition_ai_mobile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --base-href="/NutriCoach-AI/"

      - name: Upload Web build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nutricoach-mobile-web-${{ github.run_number }}
          path: nutrition_ai_mobile/build/web/
          retention-days: 30

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: nutrition_ai_mobile/build/web
          destination_dir: mobile-app